### ISSUE TITLE
Using Cucumber 7 causes cucumberTest task to fail

### ISSUE THREAD

**Issue by JamieFlournoy** [double16/gradle-cucumber-jvm-plugin#11]
Upgrading a project that uses version 0.20 of this plugin to also depend on Cucumber 7.0.0 results in the following error:

```
> Task :cucumberTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cucumberTest'.
> index is out of range 0..-1 (index = 0)
```

Here's a more detailed stacktrace:

```
Caused by: java.lang.IndexOutOfBoundsException: index is out of range 0..-1 (index = 0)
        at com.commercehub.gradle.cucumber.MasterThoughtReportGenerator$_setJsonFileUriToRelativePaths_closure2.doCall(MasterThoughtReportGenerator.groovy:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.commercehub.gradle.cucumber.MasterThoughtReportGenerator.setJsonFileUriToRelativePaths(MasterThoughtReportGenerator.groovy:44)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.commercehub.gradle.cucumber.MasterThoughtReportGenerator.setProperty(MasterThoughtReportGenerator.groovy)
        at com.commercehub.gradle.cucumber.MasterThoughtReportGenerator.generateReport(MasterThoughtReportGenerator.groovy:29)
        at com.commercehub.gradle.cucumber.ReportGenerator$generateReport.call(Unknown Source)
        at com.commercehub.gradle.cucumber.CucumberTask.executeTests(CucumberTask.groovy:100)
```

**Comment by JamieFlournoy** [comment]
It looks like the cause of this exception is pretty simple: the regex in `setJsonFileUriToRelativePaths` is looking for leading and trailing whitespace, and that no longer matches the contents of the JSON file which that method trying to edit.

https://github.com/double16/gradle-cucumber-jvm-plugin/blob/eb66c786f1606e28b6a7f9b94ec84e3e7c99de2c/src/main/groovy/com/commercehub/gradle/cucumber/MasterThoughtReportGenerator.groovy#L43

It looks like there are no tests for MasterThoughtReportGenerator.groovy, but simply forking the plugin and editing that regex to remove the `\\s` (so it starts and ends with the `.*`) fixes this.
